Hardware reset of realsense on SIGINT
MisoRobotics/realsense pull request #7
Opened 2018-07-30 23:21 UTC by zzv2

After restarting the realsense with the new v2.14.1 librealsense driver we often get this error:
```
30/07 13:01:01,549 WARNING [140468993460096] (types.cpp:57) get_xu(id=10) failed! Last Error: Input/output error
[ERROR] [1532980861.551923317]: An exception has been thrown: get_xu(id=10) failed! Last Error: Input/output error
[ERROR] [1532980861.551955229]: An exception has been thrown: get_xu(id=10) failed! Last Error: Input/output error
[FATAL] [1532980861.554830463]: Failed to load nodelet '/cameras/fryer/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[cameras/fryer/realsense2_camera-4] process has died [pid 19071, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/zzv/.ros/log/44ce9208-9433-11e8-b2d7-6045cb84d761/cameras-fryer-realsense2_camera-4.log].
log file: /home/zzv/.ros/log/44ce9208-9433-11e8-b2d7-6045cb84d761/cameras-fryer-realsense2_camera-4*.log
```
And we must unplug and replug the realsense or restart the jetson to get it to work again.
This fix calls the hardware reset function on sigint so that next time the realsense will start correctly.

2018-07-30 23:33 UTC, jrwhite1987 approved these changes

2018-07-30 23:41 UTC, rsinnet requested changes
I think it would probably be better to restart at startup rather than at shutdown. Then it would be guaranteed to reset every time.

If we do for some reason need to add support for SIGINT, it needs to be disabled when the node is initialized as shown at the bottom: http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown#Custom_SIGINT_Handler

2018-07-30 23:41 UTC, rsinnet commented on realsense2_camera/src/realsense_node_factory.cpp
> +rs2::device global_device;
No global variables. You should probably use boost to solve the problem like here: https://stackoverflow.com/questions/45137048/graceful-shutdown-on-sigint

2018-07-31 03:05 UTC, Schwo0ps commented on realsense2_camera/src/realsense_node_factory.cpp
> +void signalHandler(int signum)
It was previously `inline`, why not keep it like that.

2018-07-31 03:07 UTC, Schwo0ps commented
@rsinnet I'm not sure if we want to reset on startup. I feel like that could cause race conditions and would increase startup time. I also don't know if the `hardware_reset` function is 100% stable so it may cause issues we could avoid if it's called every startup.

2018-08-02 00:10 UTC, zzv2 commented
we actually don't want to reset on sigint, we only need to reset if there was an exception during startup. the new fix is in #10

2018-08-02 00:10 UTC, closed without merging